### ISSUE TITLE
ZMQ 2 dependency

### ISSUE THREAD

**Issue by mathieu1** [ibm-et/spark-kernel#23]
First a naive question : it seems essential that ZMQ 2.2 is installed (as opposed to say 4, see below). However, ZMQ states that 4 is backwards compatible with 2.2. Does this not mean ZMQ 4 should work?

Then, some remarks following my (casual OS X user's) perspective

* The "getting started" section's step-by-step style is great. However, extra info for setting up ZMQ 2.2 *on OS X* could include: 
  1. need to `brew install homebrew/versions/zeromq22` rather than `brew install zeromq22`
  2. If a more recent zeromq brew version is already in place, the zeromq22 keg might not link, so one might need to `brew unlink zeromq` and `brew link --force zeromq22`
* It would be very helpful to get an error at some point (while building or from the kernel) indicating that the ZMQ version is not 2.2. I failed to notice that zeromq22 did not link on install (because of pre-existing ZMQ 4), but this resulted in *no change whatsoever* in behavior when launching a notebook (with the kernel sending the final `[INFO] c.i.s.k.p.v.r.KernelMessageRelay - Relay is now fully ready to receive messages!`) except that the notebook hangs forever in the `Kernel starting, please wait...` state. 

![sparkkernel](https://cloud.githubusercontent.com/assets/7703352/5695003/429c71e8-9988-11e4-8762-39c36255d73c.png)

This makes it hard to identify the problem, especially since it's very easy to miss that zeromq22 did not link on install.

Obviously, all this becomes irrelevant if either the dependency would be updated to the current version of ZMQ or if JeroMQ would be used instead, as suggested in #1.

**Comment by rcsenkbeil** [comment]
The current implementations of the Spark Kernel and client library use [akka-zeromq](http://doc.akka.io/docs/akka/snapshot/scala/zeromq.html), an abstraction of the ZeroMQ library that exposes the library via actors. As it turns out, the akka-zeromq module uses an older version of JZMQ underneath and has a disclaimer on their documentation page:

> Note
> 
> The currently used version of zeromq-scala-bindings is only compatible with zeromq 2; zeromq 3 is not supported.

If I recall correctly, using a newer version of libzmq does not work with the akka-zeromq module.

For now, I'll just update the documentation to be a little more in-depth regarding ZeroMQ (as per your suggestion).

**Comment by rcsenkbeil** [comment]
FYI, [scala-zeromq](https://github.com/mDialog/scala-zeromq) has been the recommended migration from akka as it is implemented as an akka extension (in the same way as _akka-zeromq_).

Furthermore, it looks like there is an issue geared toward moving to JeroMQ underneath instead of JZMQ: https://github.com/mDialog/scala-zeromq/issues/23

We should keep our eyes on this.

**Comment by rcsenkbeil** [comment]
Resolved by #113.
