### ISSUE TITLE
tab completion in ipython REPL is broken.

### ISSUE THREAD

**Issue by sbromberger** [ibm-et/spark-kernel#238]
```
In [3]: val accum = sc.accum<TAB>
val accum = sc.accumaccumulableCollectionaccum
val accum = sc.accumaccumulableaccum
val accum = sc.accumaccumulatoraccum

In [3]: val accum = sc.accumaccumula
```

**Comment by lbustelo** [comment]
That is an issue with the implementation of the tab completion in Jupyter. It is a timing issue because the scala interpreter is not fast enough. We could recreate that on the python kernel if we were to slow it down. So basically, it is a client code issue.

![tabcompletion](https://cloud.githubusercontent.com/assets/2474841/12184454/edc5ced6-b55a-11e5-812e-a2ccb5eaf1a7.gif)

**Comment by sbromberger** [comment]
This is happening in ipython, not jupyter notebook, if it matters...

**Comment by lbustelo** [comment]
Yeah. Same thing.
